version: "2"
run:
  concurrency: 4
  issues-exit-code: 1
  tests: false
linters:
  enable:
    - gocritic
    - gocyclo
    - lll
    - misspell
    - nakedret
    - nilerr
    - staticcheck
    - whitespace
    - revive
  disable:
    - errcheck
  settings:
    staticcheck:
      checks:
        - all
        - -QF1008
        - -QF1001
        - -ST1003
        - -ST1011
    revive:
      severity: error
      enable-all-rules: false
      directives:
        - name: specify-disable-reason
          severity: error
      rules:
        - name: exported
          severity: error
          disabled: false
          exclude: [ "" ]
          arguments:
            - "check-private-receivers"
            - "disableStutteringCheck"
            - "disable-checks-on-constants"
            - "disable-checks-on-types"
            - "disable-checks-on-variables"

    lll:
      # Max line length, lines longer will be reported.
      # '\t' is counted as 1 character by default, and can be changed with the tab-width option.
      # Default: 120.
      line-length: 120
      # Tab width in spaces.
      # Default: 1
      tab-width: 1

  exclusions:
    generated: lax
    presets:
      - comments
      - common-false-positives
      - legacy
      - std-error-handling
    paths:
      - third_party$
      - builtin$
      - examples$
formatters:
  enable:
    - gofmt
    - goimports
  settings:
    gofmt:
      # Simplify code: gofmt with `-s` option.
      # Default: true
      simplify: false
      # Apply the rewrite rules to the source before reformatting.
      # https://pkg.go.dev/cmd/gofmt
      # Default: []
      rewrite-rules:
        - pattern: 'a[b:len(a)]'
          replacement: 'a[b:]'
    goimports:
      local-prefixes:
        - github.com/TencentBlueKing/blueking-apigateway-operator
  exclusions:
    generated: lax
    paths:
      - third_party$
      - builtin$
      - examples$