# permissions for end users to view bkgatewaystreamresources.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: clusterrole
    app.kubernetes.io/instance: bkgatewaystreamresource-viewer-role
    app.kubernetes.io/component: rbac
    app.kubernetes.io/created-by: github.com/TencentBlueKing/blueking-apigateway-operator
    app.kubernetes.io/part-of: github.com/TencentBlueKing/blueking-apigateway-operator
    app.kubernetes.io/managed-by: kustomize
  name: bkgatewaystreamresource-viewer-role
rules:
- apiGroups:
  - gateway.bk.tencent.com
  resources:
  - bkgatewaystreamresources
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - gateway.bk.tencent.com
  resources:
  - bkgatewaystreamresources/status
  verbs:
  - get
