// Code generated by MockGen. DO NOT EDIT.
// Source: getter.go

// Package mock is a generated GoMock package.
package mock

import (
	reflect "reflect"

	radixtree "github.com/TencentBlueKing/blueking-apigateway-operator/pkg/radixtree"
	registry "github.com/TencentBlueKing/blueking-apigateway-operator/pkg/registry"
	gomock "github.com/golang/mock/gomock"
)

// MockRadixTreeGetter is a mock of RadixTreeGetter interface.
type MockRadixTreeGetter struct {
	ctrl     *gomock.Controller
	recorder *MockRadixTreeGetterMockRecorder
}

// MockRadixTreeGetterMockRecorder is the mock recorder for MockRadixTreeGetter.
type MockRadixTreeGetterMockRecorder struct {
	mock *MockRadixTreeGetter
}

// NewMockRadixTreeGetter creates a new mock instance.
func NewMockRadixTreeGetter(ctrl *gomock.Controller) *MockRadixTreeGetter {
	mock := &MockRadixTreeGetter{ctrl: ctrl}
	mock.recorder = &MockRadixTreeGetterMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockRadixTreeGetter) EXPECT() *MockRadixTreeGetterMockRecorder {
	return m.recorder
}

// Get mocks base method.
func (m *MockRadixTreeGetter) Get(stage registry.StageInfo) radixtree.RadixTree {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Get", stage)
	ret0, _ := ret[0].(radixtree.RadixTree)
	return ret0
}

// Get indicates an expected call of Get.
func (mr *MockRadixTreeGetterMockRecorder) Get(stage interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Get", reflect.TypeOf((*MockRadixTreeGetter)(nil).Get), stage)
}

// RemoveNotExistStage mocks base method.
func (m *MockRadixTreeGetter) RemoveNotExistStage(existStageList []registry.StageInfo) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "RemoveNotExistStage", existStageList)
}

// RemoveNotExistStage indicates an expected call of RemoveNotExistStage.
func (mr *MockRadixTreeGetterMockRecorder) RemoveNotExistStage(existStageList interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RemoveNotExistStage", reflect.TypeOf((*MockRadixTreeGetter)(nil).RemoveNotExistStage), existStageList)
}
