name: Go

on:
  push:
    branches: [ master, develop ]
  pull_request:
    branches: [ master, develop ]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v6

    - name: Set up Go
      uses: actions/setup-go@v6
      with:
        go-version: 1.25.5

    - name: Init
      run: make init


    - name: Lint
      uses: golangci/golangci-lint-action@v9
      with:
        version: v2.11

    - name: Aqua Security Trivy
      uses: aquasecurity/trivy-action@v0.35.0
      continue-on-error: true
      with:
        scan-type: 'fs'
        scan-ref: '.'

    - name: Test
      run: |
          go install github.com/onsi/ginkgo/v2/ginkgo@v2.27.2 && make test

    - name: Integration Test
      run:  make integration
